<?php

namespace AppBundle\Repository;

/**
 * EnsembleTypePannesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsembleTypePannesRepository extends \Doctrine\ORM\EntityRepository
{
}
