<?php

namespace AppBundle\Repository;

/**
 * PanneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanneRepository extends \Doctrine\ORM\EntityRepository
{
}
