<?php

namespace AppBundle\Repository;

/**
 * TypePannesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePannesRepository extends \Doctrine\ORM\EntityRepository
{
}
