<?php

namespace AppBundle\Repository;

/**
 * TypeAlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAlerteRepository extends \Doctrine\ORM\EntityRepository
{
}
