imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     blindeuroxtest.mysql.db
        port:     3306
        dbname:   blindeuroxtest
        user:     blindeuroxtest
        password: Mathieu23
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true